### ISSUE TITLE
前后端代码分离

### ISSUE THREAD

**Issue by sevenlx** [ifintech/rd-build#4]
在开发、线上环境中，前端页面文件如何管理发布。

**Comment by sabercoding** [comment]
有好多的吖，像360有那个燕尾服编译平台。它可以做到：压缩代码，生成前端依赖文件生成cdn，语法检查，前后端分开上线啥的。貌似好多公司的前端都有的。

**Comment by sevenlx** [comment]
@sabercoding  你们前后端上线的顺序怎么处理的？

**Comment by sabercoding** [comment]
@sevenlx 我们用的框架是n年前一个人写的。前端其实并没有分离，还可以assign过去值使用，跟我们之前的前端差不多。但是前端文件分成两个文件夹，一个文件夹内文件就是开发的时候编写的，另一个是编译后的文件。线上使用的是编译后的文件夹，所以上线前需要进行编译。之后就是发布到线上，其实前端已经做了一部分的上线了。

**Comment by sabercoding** [comment]
嗯，看了下。最新做的前端功能都是已经分离的了，只要提供接口就好了。他们的js文件也按照view那样存放，require各个module，用了vue。怎么编译的还没来得及看=。=    nodejs没有接触
